version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  django:
    build:
      context: .
      dockerfile: Dockerfile.django  # Укажите путь к Dockerfile для Django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://testuser:testpass@postgres:5432/taskdb

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  # Укажите путь к Dockerfile для FastAPI
    command: uvicorn fastapi_app.main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./fastapi_app:/app/fastapi_app  # Монтируем только папку fastapi_app
    ports:
      - "8001:8001"
    depends_on:
      - kafka

  kafka_consumer:
    build:
      context: .
      dockerfile: Dockerfile.kafka_consumer  # Укажите путь к Dockerfile для Kafka Consumer
    command: python kafka_consumer/consumer.py
    volumes:
      - ./kafka_consumer:/app/kafka_consumer  # Монтируем только папку kafka_consumer
    depends_on:
      - kafka

volumes:
  postgres_data: