# Используем официальный образ Python
FROM python:3.10-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем зависимости
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код
COPY kafka_consumer/ ./kafka_consumer/

# Команда для запуска
CMD ["python", "kafka_consumer/consumer.py"]